In [1]:
import pandas as pd

In [4]:

df = pd.read_csv('/Users/yhra/Documents/Master/Semester_3/BATIP/Supernova_project/Data/Pantheon+SH0ES_STAT+SYS.cov')
df.describe()

               1701
count  2.893401e+06
mean   2.356060e-05
std    1.894494e-03
min   -3.172511e-02
25%   -4.801300e-04
50%   -5.390000e-06
75%    4.612800e-04
max    3.910331e-01

In [6]:
df = pd.read_csv('/Users/yhra/Documents/Master/Semester_3/BATIP/Supernova_project/Data/Pantheon+SH0ES_STATONLY.cov', sep='\s+', header=0)
df.describe()

               1701
count  2.893401e+06
mean   1.938711e-05
std    9.368181e-04
min    0.000000e+00
25%    0.000000e+00
50%    0.000000e+00
75%    0.000000e+00
max    3.847721e-01

In [8]:
df = pd.read_csv('/Users/yhra/Documents/Master/Semester_3/BATIP/Supernova_project/Data/Pantheon+SH0ES.dat', sep='\s+', header=0)
df.describe()

,IDSURVEY,zHD,zHDERR,zCMB,zCMBERR,zHEL,zHELERR,m_b_corr,m_b_corr_err_DIAG,MU_SH0ES,...,PKMJDERR,NDOF,FITCHI2,FITPROB,m_b_corr_err_RAW,m_b_corr_err_VPEC,biasCor_m_b,biasCorErr_m_b,biasCor_m_b_COVSCALE,biasCor_m_b_COVADD
count,1701.000000,1701.000000,1701.000000,1701.000000,1701.000000,1701.00000,1701.000000,1701.000000,1701.000000,1701.000000,...,1701.000000,1701.000000,1701.000000,1701.000000,1701.000000,1701.000000,1701.000000,1701.000000,1701.000000,1701.000000
mean,37.017637,0.221229,0.001840,0.221090,0.001155,0.22143,0.001155,19.083629,0.240920,38.336629,...,0.384440,36.499118,47.227484,0.469040,0.104899,0.061886,-0.009629,0.004541,0.972350,0.008889
std,45.916840,0.249271,0.002593,0.249337,0.002774,0.24944,0.002774,3.374499,0.098815,3.374499,...,0.473585,23.891781,67.434767,0.378961,0.055224,0.096221,0.074649,0.005048,0.089824,0.009789
min,1.000000,0.001220,0.000840,0.001220,0.000000,0.00082,0.000000,9.745710,0.111583,28.998700,...,0.004500,0.000000,0.219440,0.000000,0.034300,0.004300,-0.535600,0.000000,0.164000,0.000000
25%,4.000000,0.027730,0.000860,0.027210,0.000020,0.02716,0.000020,16.036200,0.178788,35.289200,...,0.138200,20.000000,18.316200,0.062870,0.065700,0.010800,-0.050900,0.002000,1.000000,0.003000
50%,15.000000,0.163750,0.001030,0.163570,0.000150,0.16470,0.000150,20.076300,0.217323,39.329300,...,0.269100,34.000000,33.036300,0.441920,0.087100,0.028800,0.001500,0.003000,1.000000,0.006000
75%,57.000000,0.328680,0.001480,0.328590,0.001000,0.32961,0.001000,21.824800,0.278656,41.077800,...,0.483700,48.000000,51.953600,0.865830,0.124800,0.076900,0.034500,0.005000,1.000000,0.012000
max,150.000000,2.261370,0.040060,2.261300,0.040000,2.26000,0.040000,26.929800,1.517230,46.182800,...,6.310000,280.000000,1106.220000,1.000000,0.493300,1.496000,0.365300,0.050000,1.000000,0.063000